### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DutchPete** [bencodezen/obsidian-md-night-owl-theme#3]
In the ReadME you state that customization can be done by modifying the `Night Owl.css` file. I think that is a "bad" suggestion because, as you state, update will override the customizations. So it is better not to mention this possibility.

A better alternative is to make use of snippets, which are in a separate folder and never get overridden by a theme update.
You have not mentioned the possibility of snippets.

BTW, thanks for a very nice theme!

**Comment by bencodezen** [comment]
@DutchPete Great point! I shall update it now.
