### ISSUE TITLE
Style Settings support?

### ISSUE THREAD

**Issue by leejunweisg** [bencodezen/obsidian-md-night-owl-theme#4]
I love this theme! May I know if there are any plans to add Style Settings support? Thanks!

**Comment by xaperret** [comment]
I'm seconding this, really like this theme it could be great if it was supporting with https://github.com/mgmeyers/obsidian-style-settings

**Comment by bencodezen** [comment]
Thanks for the request! Adding it to the queue!

**Comment by bencodezen** [comment]
@leejunweisg and @xaperret - Sorry for the long wait, but I've set up plugin integration with Style Settings successfully!

I've only added some basic color configuration to start, but if you have a specific list of properties I can prioritize, please feel free to file new issues and I'd be happy to add them in!

Appreciate the inspiration and thanks for your patience!
